spring:
  jpa:
    database: oracle
  #profiles:
    #active:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@20.2.15.18:1521/gxdb
    username: JHGX
    password: JHGX001
    initial-size: 2
    max-active: 500
    min-idle: 20
    max-wait: 60000
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    max-open-prepared-statements: 20
    validation-query: SELECT 1 FROM DUAL
    validation-query-timeout: 2000
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    max-evictable-idle-time-millis: 300000
  application:
    name: travelspeed
  #cache:
    #ehcache:
      #config: classpath:static/ehcache.xml
    #type: ehcache
redis:
  cluster:
    nodes:
        - 20.2.11.16:7000
        - 20.2.11.16:7001
        - 20.2.11.17:7000
        - 20.2.11.17:7001
        - 20.2.11.21:7000
        - 20.2.11.21:7001
    max-redirects: 6
    #jedis:
      #pool:
        #max-active: 8
        #max-idle: 300
    timeout: 5000
      #commandTimeout: 5000
      #expireSeconds: 120

    #最大空闲数
    #maxIdle: 300
    #连接池的最大数据库连接数。设为0表示无限制,如果是jedis 2.4以后用redis.maxTotal
    #redis.maxActive=600
    #控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
    #maxTotal: 1000
    #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
    #maxWaitMillis: 1000
    #连接的最小空闲时间 默认1800000毫秒(30分钟)
    #minEvictableIdleTimeMillis: 300000
    #每次释放连接的最大数目,默认3
    #numTestsPerEvictionRun: 1024
    #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
    #timeBetweenEvictionRunsMillis: 30000
    #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
    #testOnBorrow: true
    #在空闲时检查有效性, 默认false
    #testWhileIdle: true
#默认使用配置



#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.hisense.springboot.model
  mapperLocations: classpath:mybatis/mapping/*.xml
  #configuration:
      #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:log4j2.xml
server:
  port: 8600